export type SeedSeries = {
  title: string;
  slug: string;
  description: string;
  releaseYear: number;
  status: "Ended" | "Returning" | "Continuing";
  network: string;
  creator: string;
  cast: string;
  genres: string[];
};

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const show = (
  title: string,
  releaseYear: number,
  status: SeedSeries["status"],
  network: string,
  creator: string,
  cast: string,
  genres: string[],
  description: string,
): SeedSeries => ({
  title,
  slug: slugify(title),
  description,
  releaseYear,
  status,
  network,
  creator,
  cast,
  genres,
});

export const seedSeries: SeedSeries[] = [
  show("Breaking Bad", 2008, "Ended", "AMC", "Vince Gilligan", "Bryan Cranston, Aaron Paul, Anna Gunn", ["Crime", "Drama", "Thriller"], "A chemistry teacher turns to making meth and is pulled deeper into crime."),
  show("Better Call Saul", 2015, "Ended", "AMC", "Vince Gilligan, Peter Gould", "Bob Odenkirk, Rhea Seehorn, Jonathan Banks", ["Crime", "Drama"], "A struggling lawyer slowly transforms into a morally flexible criminal attorney."),
  show("The Sopranos", 1999, "Ended", "HBO", "David Chase", "James Gandolfini, Edie Falco, Lorraine Bracco", ["Crime", "Drama"], "A New Jersey mob boss balances family life, panic attacks, and organized crime."),
  show("The Wire", 2002, "Ended", "HBO", "David Simon", "Dominic West, Lance Reddick, Sonja Sohn", ["Crime", "Drama"], "Baltimore institutions are examined through police, schools, politics, media, and the drug trade."),
  show("Game of Thrones", 2011, "Ended", "HBO", "David Benioff, D. B. Weiss", "Emilia Clarke, Kit Harington, Peter Dinklage", ["Adventure", "Drama", "Fantasy"], "Noble families fight for power while an ancient threat grows beyond the wall."),
  show("House of the Dragon", 2022, "Returning", "HBO", "Ryan Condal, George R. R. Martin", "Emma D'Arcy, Olivia Cooke, Matt Smith", ["Adventure", "Drama", "Fantasy"], "A Targaryen succession crisis pushes a dragon-riding dynasty toward civil war."),
  show("Stranger Things", 2016, "Returning", "Netflix", "Matt Duffer, Ross Duffer", "Millie Bobby Brown, Finn Wolfhard, David Harbour", ["Drama", "Fantasy", "Horror"], "Kids in a small town face secret experiments and monsters from another dimension."),
  show("The Crown", 2016, "Ended", "Netflix", "Peter Morgan", "Claire Foy, Olivia Colman, Imelda Staunton", ["Drama", "History"], "The reign of Queen Elizabeth II is explored through politics, family, and public duty."),
  show("The Mandalorian", 2019, "Returning", "Disney+", "Jon Favreau", "Pedro Pascal, Katee Sackhoff, Carl Weathers", ["Action", "Adventure", "Science Fiction"], "A lone bounty hunter protects a mysterious child across the outer reaches of the galaxy."),
  show("Andor", 2022, "Returning", "Disney+", "Tony Gilroy", "Diego Luna, Stellan Skarsgard, Genevieve O'Reilly", ["Action", "Adventure", "Science Fiction"], "A thief becomes part of a growing rebellion against imperial control."),
  show("Lost", 2004, "Ended", "ABC", "J. J. Abrams, Damon Lindelof, Jeffrey Lieber", "Matthew Fox, Evangeline Lilly, Terry O'Quinn", ["Adventure", "Drama", "Mystery"], "Plane crash survivors discover that their island hides dangerous and impossible secrets."),
  show("The X-Files", 1993, "Ended", "Fox", "Chris Carter", "David Duchovny, Gillian Anderson, Mitch Pileggi", ["Drama", "Mystery", "Science Fiction"], "FBI agents investigate paranormal cases while uncovering a wider conspiracy."),
  show("Twin Peaks", 1990, "Ended", "ABC", "David Lynch, Mark Frost", "Kyle MacLachlan, Michael Ontkean, Madchen Amick", ["Crime", "Drama", "Mystery"], "A murder investigation exposes surreal secrets in a quiet logging town."),
  show("The Twilight Zone", 1959, "Ended", "CBS", "Rod Serling", "Rod Serling, Robert McCord, Jay Overholts", ["Drama", "Fantasy", "Science Fiction"], "Anthology stories use strange scenarios to reveal human fears and choices."),
  show("Black Mirror", 2011, "Returning", "Netflix", "Charlie Brooker", "Daniel Lapaine, Hannah John-Kamen, Michaela Coel", ["Drama", "Science Fiction", "Thriller"], "Standalone stories explore the uneasy consequences of technology and modern life."),
  show("Westworld", 2016, "Ended", "HBO", "Jonathan Nolan, Lisa Joy", "Evan Rachel Wood, Thandiwe Newton, Jeffrey Wright", ["Drama", "Mystery", "Science Fiction"], "A futuristic theme park becomes unstable as artificial hosts gain awareness."),
  show("Succession", 2018, "Ended", "HBO", "Jesse Armstrong", "Brian Cox, Jeremy Strong, Sarah Snook", ["Comedy", "Drama"], "A wealthy media family fights for control as its patriarch's power weakens."),
  show("Mad Men", 2007, "Ended", "AMC", "Matthew Weiner", "Jon Hamm, Elisabeth Moss, Christina Hendricks", ["Drama"], "Advertising executives navigate ambition, identity, and social change in 1960s New York."),
  show("The Office", 2005, "Ended", "NBC", "Greg Daniels", "Steve Carell, Rainn Wilson, John Krasinski", ["Comedy"], "A paper company branch turns everyday office life into awkward comedy."),
  show("Parks and Recreation", 2009, "Ended", "NBC", "Greg Daniels, Michael Schur", "Amy Poehler, Nick Offerman, Rashida Jones", ["Comedy"], "A cheerful public servant and her coworkers try to improve their Indiana town."),
  show("Friends", 1994, "Ended", "NBC", "David Crane, Marta Kauffman", "Jennifer Aniston, Courteney Cox, Matthew Perry", ["Comedy", "Romance"], "Six friends in New York share relationships, careers, and constant apartment visits."),
  show("Seinfeld", 1989, "Ended", "NBC", "Larry David, Jerry Seinfeld", "Jerry Seinfeld, Julia Louis-Dreyfus, Jason Alexander", ["Comedy"], "Four self-absorbed New Yorkers turn everyday irritations into comic disasters."),
  show("Frasier", 1993, "Ended", "NBC", "David Angell, Peter Casey, David Lee", "Kelsey Grammer, David Hyde Pierce, Jane Leeves", ["Comedy"], "A radio psychiatrist rebuilds his life in Seattle with family and colleagues."),
  show("Cheers", 1982, "Ended", "NBC", "James Burrows, Glen Charles, Les Charles", "Ted Danson, Shelley Long, Rhea Perlman", ["Comedy", "Drama"], "Regulars at a Boston bar find friendship, rivalry, and romance over drinks."),
  show("The Simpsons", 1989, "Continuing", "Fox", "Matt Groening", "Dan Castellaneta, Julie Kavner, Nancy Cartwright", ["Animation", "Comedy"], "A Springfield family satirizes American life through endless misadventures."),
  show("Futurama", 1999, "Returning", "Hulu", "Matt Groening, David X. Cohen", "Billy West, Katey Sagal, John DiMaggio", ["Animation", "Comedy", "Science Fiction"], "A delivery crew in the far future stumbles through space, robots, and bureaucracy."),
  show("Rick and Morty", 2013, "Returning", "Adult Swim", "Dan Harmon, Justin Roiland", "Chris Parnell, Spencer Grammer, Sarah Chalke", ["Animation", "Adventure", "Comedy"], "A chaotic scientist drags his grandson through dangerous multiverse adventures."),
  show("BoJack Horseman", 2014, "Ended", "Netflix", "Raphael Bob-Waksberg", "Will Arnett, Amy Sedaris, Alison Brie", ["Animation", "Comedy", "Drama"], "A washed-up actor confronts fame, addiction, and the harm he causes others."),
  show("Avatar: The Last Airbender", 2005, "Ended", "Nickelodeon", "Michael Dante DiMartino, Bryan Konietzko", "Zach Tyler Eisen, Mae Whitman, Jack De Sena", ["Action", "Adventure", "Animation"], "A young airbender must master the elements to stop a conquering nation."),
  show("Arcane", 2021, "Returning", "Netflix", "Christian Linke, Alex Yee", "Hailee Steinfeld, Ella Purnell, Kevin Alejandro", ["Action", "Adventure", "Animation"], "Two sisters are caught in the conflict between a wealthy city and its oppressed undercity."),
  show("The Last of Us", 2023, "Returning", "HBO", "Craig Mazin, Neil Druckmann", "Pedro Pascal, Bella Ramsey, Anna Torv", ["Adventure", "Drama", "Horror"], "A hardened survivor escorts a teenager across a post-pandemic America."),
  show("Chernobyl", 2019, "Ended", "HBO", "Craig Mazin", "Jared Harris, Stellan Skarsgard, Emily Watson", ["Drama", "History"], "Scientists and officials confront the disaster and cover-up around a nuclear explosion."),
  show("Band of Brothers", 2001, "Ended", "HBO", "Tom Hanks, Steven Spielberg", "Damian Lewis, Ron Livingston, Donnie Wahlberg", ["Drama", "History", "War"], "Easy Company moves through World War II from training to the war's end."),
  show("The Pacific", 2010, "Ended", "HBO", "Bruce C. McKenna", "James Badge Dale, Joseph Mazzello, Jon Seda", ["Drama", "History", "War"], "Marines endure brutal campaigns across the Pacific theater during World War II."),
  show("Sherlock", 2010, "Ended", "BBC", "Mark Gatiss, Steven Moffat", "Benedict Cumberbatch, Martin Freeman, Una Stubbs", ["Crime", "Drama", "Mystery"], "A modern Holmes and Watson solve complex crimes in contemporary London."),
  show("Doctor Who", 2005, "Continuing", "BBC", "Sydney Newman, Russell T Davies", "David Tennant, Matt Smith, Jodie Whittaker", ["Adventure", "Drama", "Science Fiction"], "A time-traveling alien protects worlds with changing companions and faces."),
  show("Downton Abbey", 2010, "Ended", "ITV", "Julian Fellowes", "Hugh Bonneville, Michelle Dockery, Maggie Smith", ["Drama", "History", "Romance"], "An aristocratic household and its staff navigate social change in early twentieth-century England."),
  show("Peaky Blinders", 2013, "Ended", "BBC", "Steven Knight", "Cillian Murphy, Paul Anderson, Helen McCrory", ["Crime", "Drama"], "A Birmingham gang family expands its power after World War I."),
  show("Luther", 2010, "Ended", "BBC", "Neil Cross", "Idris Elba, Dermot Crowley, Ruth Wilson", ["Crime", "Drama", "Mystery"], "A brilliant detective pursues violent criminals while wrestling with his own darkness."),
  show("Broadchurch", 2013, "Ended", "ITV", "Chris Chibnall", "David Tennant, Olivia Colman, Jodie Whittaker", ["Crime", "Drama", "Mystery"], "A child's murder shakes a seaside town and exposes hidden grief."),
  show("Fleabag", 2016, "Ended", "BBC", "Phoebe Waller-Bridge", "Phoebe Waller-Bridge, Sian Clifford, Olivia Colman", ["Comedy", "Drama"], "A sharp, grieving Londoner navigates desire, family, and self-sabotage."),
  show("Killing Eve", 2018, "Ended", "BBC America", "Phoebe Waller-Bridge", "Sandra Oh, Jodie Comer, Fiona Shaw", ["Action", "Drama", "Thriller"], "An intelligence officer and an assassin become dangerously fascinated with each other."),
  show("The Americans", 2013, "Ended", "FX", "Joe Weisberg", "Keri Russell, Matthew Rhys, Noah Emmerich", ["Crime", "Drama", "Thriller"], "Soviet spies live as an American family while Cold War pressure intensifies."),
  show("Homeland", 2011, "Ended", "Showtime", "Howard Gordon, Alex Gansa", "Claire Danes, Mandy Patinkin, Damian Lewis", ["Crime", "Drama", "Thriller"], "A CIA officer tracks threats while battling personal and political instability."),
  show("24", 2001, "Ended", "Fox", "Joel Surnow, Robert Cochran", "Kiefer Sutherland, Mary Lynn Rajskub, Carlos Bernard", ["Action", "Crime", "Drama"], "Counterterrorism agent Jack Bauer races through crises in real time."),
  show("Prison Break", 2005, "Ended", "Fox", "Paul Scheuring", "Wentworth Miller, Dominic Purcell, Sarah Wayne Callies", ["Action", "Crime", "Drama"], "A man gets himself imprisoned to break out his wrongly convicted brother."),
  show("Dexter", 2006, "Ended", "Showtime", "James Manos Jr.", "Michael C. Hall, Jennifer Carpenter, David Zayas", ["Crime", "Drama", "Mystery"], "A forensic analyst secretly channels his violent urges toward killers."),
  show("True Detective", 2014, "Returning", "HBO", "Nic Pizzolatto", "Matthew McConaughey, Woody Harrelson, Mahershala Ali", ["Crime", "Drama", "Mystery"], "Different investigators confront crimes that reveal obsession, corruption, and memory."),
  show("Fargo", 2014, "Returning", "FX", "Noah Hawley", "Billy Bob Thornton, Martin Freeman, Allison Tolman", ["Crime", "Drama", "Comedy"], "Anthology crime stories unfold with dark humor and escalating consequences."),
  show("Mr. Robot", 2015, "Ended", "USA Network", "Sam Esmail", "Rami Malek, Christian Slater, Carly Chaikin", ["Crime", "Drama", "Thriller"], "A hacker joins a revolutionary plot while questioning reality and control."),
  show("The Handmaid's Tale", 2017, "Returning", "Hulu", "Bruce Miller", "Elisabeth Moss, Yvonne Strahovski, Ann Dowd", ["Drama", "Science Fiction", "Thriller"], "A woman resists a theocratic regime that controls fertility and identity."),
  show("The Boys", 2019, "Returning", "Prime Video", "Eric Kripke", "Karl Urban, Jack Quaid, Antony Starr", ["Action", "Comedy", "Crime"], "A vigilante group targets corrupt superheroes backed by corporate power."),
  show("Invincible", 2021, "Returning", "Prime Video", "Robert Kirkman", "Steven Yeun, Sandra Oh, J. K. Simmons", ["Action", "Adventure", "Animation"], "A teen superhero discovers harsh truths about legacy, violence, and family."),
  show("The Expanse", 2015, "Ended", "Syfy, Prime Video", "Mark Fergus, Hawk Ostby", "Steven Strait, Dominique Tipper, Wes Chatham", ["Drama", "Mystery", "Science Fiction"], "A fragile solar system faces conspiracy and conflict after a mysterious discovery."),
  show("Battlestar Galactica", 2004, "Ended", "Syfy", "Ronald D. Moore", "Edward James Olmos, Mary McDonnell, Katee Sackhoff", ["Action", "Adventure", "Science Fiction"], "Human survivors flee machine enemies while searching for a new home."),
  show("Firefly", 2002, "Ended", "Fox", "Joss Whedon", "Nathan Fillion, Gina Torres, Alan Tudyk", ["Adventure", "Drama", "Science Fiction"], "A renegade crew takes risky jobs on the edge of a future frontier."),
  show("Star Trek: The Next Generation", 1987, "Ended", "Syndication", "Gene Roddenberry", "Patrick Stewart, Jonathan Frakes, Brent Spiner", ["Adventure", "Drama", "Science Fiction"], "The Enterprise crew explores space while facing ethical and diplomatic challenges."),
  show("Star Trek: Deep Space Nine", 1993, "Ended", "Syndication", "Rick Berman, Michael Piller", "Avery Brooks, Nana Visitor, Rene Auberjonois", ["Action", "Drama", "Science Fiction"], "A space station near a wormhole becomes central to politics, faith, and war."),
  show("Star Trek: Voyager", 1995, "Ended", "UPN", "Rick Berman, Michael Piller, Jeri Taylor", "Kate Mulgrew, Robert Beltran, Roxann Dawson", ["Adventure", "Drama", "Science Fiction"], "A Starfleet crew stranded far from home searches for a path back."),
  show("The Walking Dead", 2010, "Ended", "AMC", "Frank Darabont", "Andrew Lincoln, Norman Reedus, Melissa McBride", ["Drama", "Horror", "Thriller"], "Survivors of a zombie outbreak struggle with danger from both the dead and living."),
  show("Fear the Walking Dead", 2015, "Ended", "AMC", "Robert Kirkman, Dave Erickson", "Kim Dickens, Frank Dillane, Alycia Debnam-Carey", ["Drama", "Horror", "Thriller"], "Families face the early collapse of society during a zombie outbreak."),
  show("Supernatural", 2005, "Ended", "The CW", "Eric Kripke", "Jared Padalecki, Jensen Ackles, Misha Collins", ["Drama", "Fantasy", "Horror"], "Two brothers hunt monsters, demons, and cosmic threats across America."),
  show("Buffy the Vampire Slayer", 1997, "Ended", "The WB", "Joss Whedon", "Sarah Michelle Gellar, Nicholas Brendon, Alyson Hannigan", ["Action", "Drama", "Fantasy"], "A teenage chosen one battles vampires while trying to live a normal life."),
  show("Angel", 1999, "Ended", "The WB", "Joss Whedon, David Greenwalt", "David Boreanaz, Charisma Carpenter, Alexis Denisof", ["Action", "Drama", "Fantasy"], "A vampire seeking redemption helps the helpless in Los Angeles."),
  show("The Vampire Diaries", 2009, "Ended", "The CW", "Kevin Williamson, Julie Plec", "Nina Dobrev, Paul Wesley, Ian Somerhalder", ["Drama", "Fantasy", "Romance"], "A small town is drawn into vampire romance, family secrets, and supernatural conflict."),
  show("The Witcher", 2019, "Returning", "Netflix", "Lauren Schmidt Hissrich", "Henry Cavill, Anya Chalotra, Freya Allan", ["Action", "Adventure", "Fantasy"], "A monster hunter, sorceress, and princess are bound by destiny on a dangerous continent."),
  show("Wednesday", 2022, "Returning", "Netflix", "Alfred Gough, Miles Millar", "Jenna Ortega, Gwendoline Christie, Emma Myers", ["Comedy", "Fantasy", "Mystery"], "Wednesday Addams investigates murders and family secrets at a school for outcasts."),
  show("The Umbrella Academy", 2019, "Ended", "Netflix", "Steve Blackman", "Elliot Page, Tom Hopper, David Castaneda", ["Action", "Adventure", "Comedy"], "Estranged superpowered siblings reunite to stop apocalyptic threats."),
  show("The Queen's Gambit", 2020, "Ended", "Netflix", "Scott Frank, Allan Scott", "Anya Taylor-Joy, Bill Camp, Marielle Heller", ["Drama"], "A chess prodigy rises through competition while battling addiction and loneliness."),
  show("Ozark", 2017, "Ended", "Netflix", "Bill Dubuque, Mark Williams", "Jason Bateman, Laura Linney, Sofia Hublitz", ["Crime", "Drama", "Thriller"], "A financial adviser moves his family to launder money for a cartel."),
  show("Narcos", 2015, "Ended", "Netflix", "Chris Brancato, Carlo Bernard, Doug Miro", "Wagner Moura, Pedro Pascal, Boyd Holbrook", ["Crime", "Drama"], "Cartel power and law enforcement collide during the rise of drug empires."),
  show("Mindhunter", 2017, "Ended", "Netflix", "Joe Penhall", "Jonathan Groff, Holt McCallany, Anna Torv", ["Crime", "Drama", "Thriller"], "FBI agents interview serial killers to build new methods of criminal profiling."),
  show("Dark", 2017, "Ended", "Netflix", "Baran bo Odar, Jantje Friese", "Louis Hofmann, Lisa Vicari, Maja Schone", ["Crime", "Drama", "Science Fiction"], "A German town's missing children reveal time loops and family secrets."),
  show("Money Heist", 2017, "Ended", "Netflix", "Alex Pina", "Ursula Corbero, Alvaro Morte, Itziar Ituno", ["Action", "Crime", "Drama"], "A criminal mastermind directs elaborate heists with a team using code names."),
  show("Squid Game", 2021, "Returning", "Netflix", "Hwang Dong-hyuk", "Lee Jung-jae, Park Hae-soo, Jung Ho-yeon", ["Drama", "Thriller"], "Debt-ridden players enter deadly children's games for a massive cash prize."),
  show("Kingdom", 2019, "Returning", "Netflix", "Kim Eun-hee", "Ju Ji-hoon, Ryu Seung-ryong, Bae Doona", ["Action", "Drama", "Horror"], "A prince investigates a plague of the dead amid political intrigue in Joseon Korea."),
  show("The Bear", 2022, "Returning", "FX", "Christopher Storer", "Jeremy Allen White, Ayo Edebiri, Ebon Moss-Bachrach", ["Comedy", "Drama"], "A fine-dining chef returns home to run his family's chaotic sandwich shop."),
  show("Ted Lasso", 2020, "Ended", "Apple TV+", "Bill Lawrence, Jason Sudeikis, Brendan Hunt, Joe Kelly", "Jason Sudeikis, Hannah Waddingham, Brett Goldstein", ["Comedy", "Drama"], "An optimistic American coach leads an English football club despite little experience."),
  show("Severance", 2022, "Returning", "Apple TV+", "Dan Erickson", "Adam Scott, Britt Lower, Patricia Arquette", ["Drama", "Mystery", "Science Fiction"], "Office workers discover troubling secrets after separating work memories from personal lives."),
  show("Foundation", 2021, "Returning", "Apple TV+", "David S. Goyer, Josh Friedman", "Jared Harris, Lee Pace, Lou Llobell", ["Drama", "Science Fiction"], "Exiles try to preserve knowledge as a galactic empire begins to collapse."),
  show("For All Mankind", 2019, "Returning", "Apple TV+", "Ronald D. Moore, Matt Wolpert, Ben Nedivi", "Joel Kinnaman, Shantel VanSanten, Wrenn Schmidt", ["Drama", "Science Fiction"], "An alternate space race keeps pushing astronauts and nations into new frontiers."),
  show("The Morning Show", 2019, "Returning", "Apple TV+", "Jay Carson", "Jennifer Aniston, Reese Witherspoon, Billy Crudup", ["Drama"], "A television newsroom faces scandal, ambition, and shifting public trust."),
  show("Yellowstone", 2018, "Ended", "Paramount Network", "Taylor Sheridan, John Linson", "Kevin Costner, Luke Grimes, Kelly Reilly", ["Drama", "Western"], "A powerful ranching family fights to protect its land from rivals and politics."),
  show("1883", 2021, "Ended", "Paramount+", "Taylor Sheridan", "Sam Elliott, Tim McGraw, Faith Hill", ["Drama", "Western"], "A family journeys west through danger while seeking a future on the frontier."),
  show("1923", 2022, "Returning", "Paramount+", "Taylor Sheridan", "Harrison Ford, Helen Mirren, Brandon Sklenar", ["Drama", "Western"], "A new generation of a ranching family faces drought, violence, and changing times."),
  show("Deadwood", 2004, "Ended", "HBO", "David Milch", "Timothy Olyphant, Ian McShane, Molly Parker", ["Crime", "Drama", "Western"], "A lawless mining camp grows into a town amid ambition and violence."),
  show("Justified", 2010, "Ended", "FX", "Graham Yost", "Timothy Olyphant, Walton Goggins, Joelle Carter", ["Action", "Crime", "Drama"], "A U.S. Marshal returns to Kentucky and confronts criminals from his past."),
  show("The Shield", 2002, "Ended", "FX", "Shawn Ryan", "Michael Chiklis, Walton Goggins, CCH Pounder", ["Crime", "Drama", "Thriller"], "A corrupt police strike team blurs justice, power, and survival in Los Angeles."),
  show("Sons of Anarchy", 2008, "Ended", "FX", "Kurt Sutter", "Charlie Hunnam, Katey Sagal, Ron Perlman", ["Crime", "Drama", "Thriller"], "An outlaw motorcycle club struggles with loyalty, violence, and family legacy."),
  show("The Leftovers", 2014, "Ended", "HBO", "Damon Lindelof, Tom Perrotta", "Justin Theroux, Carrie Coon, Amy Brenneman", ["Drama", "Fantasy", "Mystery"], "A community lives with grief after a sudden unexplained global disappearance."),
  show("Watchmen", 2019, "Ended", "HBO", "Damon Lindelof", "Regina King, Yahya Abdul-Mateen II, Jeremy Irons", ["Action", "Drama", "Mystery"], "Masked justice and buried history collide in an alternate modern America."),
  show("Hannibal", 2013, "Ended", "NBC", "Bryan Fuller", "Mads Mikkelsen, Hugh Dancy, Laurence Fishburne", ["Crime", "Drama", "Horror"], "An FBI profiler forms a dangerous bond with a brilliant psychiatrist and killer."),
  show("House", 2004, "Ended", "Fox", "David Shore", "Hugh Laurie, Lisa Edelstein, Omar Epps", ["Drama", "Mystery"], "A brilliant, abrasive doctor solves rare medical cases with unconventional methods."),
  show("Grey's Anatomy", 2005, "Continuing", "ABC", "Shonda Rhimes", "Ellen Pompeo, Chandra Wilson, James Pickens Jr.", ["Drama", "Romance"], "Doctors at a Seattle hospital face medical crises and personal entanglements."),
  show("ER", 1994, "Ended", "NBC", "Michael Crichton", "Anthony Edwards, George Clooney, Julianna Margulies", ["Drama"], "Emergency room staff confront intense cases and personal lives in Chicago."),
  show("The West Wing", 1999, "Ended", "NBC", "Aaron Sorkin", "Martin Sheen, Allison Janney, Bradley Whitford", ["Drama"], "White House staff navigate policy, crises, and idealism under a principled president."),
  show("Veep", 2012, "Ended", "HBO", "Armando Iannucci", "Julia Louis-Dreyfus, Anna Chlumsky, Tony Hale", ["Comedy"], "A vice president and her team stumble through ambition, insults, and political chaos."),
  show("Community", 2009, "Ended", "NBC", "Dan Harmon", "Joel McHale, Gillian Jacobs, Danny Pudi", ["Comedy"], "A study group at a community college becomes a strange chosen family."),
  show("Brooklyn Nine-Nine", 2013, "Ended", "Fox, NBC", "Dan Goor, Michael Schur", "Andy Samberg, Andre Braugher, Stephanie Beatriz", ["Comedy", "Crime"], "Detectives in a Brooklyn precinct solve cases with heart and absurdity."),
  show("How I Met Your Mother", 2005, "Ended", "CBS", "Carter Bays, Craig Thomas", "Josh Radnor, Jason Segel, Cobie Smulders", ["Comedy", "Romance"], "A man recounts years of friendship and dating before meeting his children's mother."),
];
