export type SeedMovie = {
  title: string;
  slug: string;
  description: string;
  releaseYear: number;
  durationMinutes: number;
  director: string;
  writer?: string;
  cast: string;
  genres: string[];
};

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const movie = (
  title: string,
  releaseYear: number,
  durationMinutes: number,
  director: string,
  writer: string,
  cast: string,
  genres: string[],
  description: string,
): SeedMovie => ({
  title,
  slug: slugify(title),
  description,
  releaseYear,
  durationMinutes,
  director,
  writer,
  cast,
  genres,
});

export const seedMovies: SeedMovie[] = [
  movie("The Godfather", 1972, 175, "Francis Ford Coppola", "Mario Puzo, Francis Ford Coppola", "Marlon Brando, Al Pacino, James Caan", ["Crime", "Drama"], "A crime family struggles with loyalty, succession, and power in postwar America."),
  movie("The Shawshank Redemption", 1994, 142, "Frank Darabont", "Frank Darabont", "Tim Robbins, Morgan Freeman, Bob Gunton", ["Drama"], "Two imprisoned men find friendship and purpose across decades behind bars."),
  movie("Pulp Fiction", 1994, 154, "Quentin Tarantino", "Quentin Tarantino, Roger Avary", "John Travolta, Uma Thurman, Samuel L. Jackson", ["Crime", "Drama"], "Interlocking Los Angeles crime stories collide with dark humor and sudden violence."),
  movie("The Dark Knight", 2008, 152, "Christopher Nolan", "Jonathan Nolan, Christopher Nolan", "Christian Bale, Heath Ledger, Aaron Eckhart", ["Action", "Crime", "Thriller"], "Batman faces a chaotic criminal whose plans test Gotham's moral limits."),
  movie("Schindler's List", 1993, 195, "Steven Spielberg", "Steven Zaillian", "Liam Neeson, Ben Kingsley, Ralph Fiennes", ["Drama", "History", "War"], "A businessman uses his factory to protect Jewish workers during the Holocaust."),
  movie("12 Angry Men", 1957, 96, "Sidney Lumet", "Reginald Rose", "Henry Fonda, Lee J. Cobb, Martin Balsam", ["Drama"], "A jury room debate reveals prejudice, doubt, and the weight of reasonable evidence."),
  movie("The Lord of the Rings: The Fellowship of the Ring", 2001, 178, "Peter Jackson", "Fran Walsh, Philippa Boyens, Peter Jackson", "Elijah Wood, Ian McKellen, Viggo Mortensen", ["Adventure", "Fantasy"], "A young hobbit joins a fellowship charged with carrying a dangerous ring toward Mordor."),
  movie("The Lord of the Rings: The Two Towers", 2002, 179, "Peter Jackson", "Fran Walsh, Philippa Boyens, Peter Jackson", "Elijah Wood, Ian McKellen, Viggo Mortensen", ["Adventure", "Fantasy"], "The fellowship is scattered as Middle-earth prepares for a decisive war."),
  movie("The Lord of the Rings: The Return of the King", 2003, 201, "Peter Jackson", "Fran Walsh, Philippa Boyens, Peter Jackson", "Elijah Wood, Ian McKellen, Viggo Mortensen", ["Adventure", "Fantasy"], "Heroes make their final stand while the ring nears its destruction."),
  movie("Forrest Gump", 1994, 142, "Robert Zemeckis", "Eric Roth", "Tom Hanks, Robin Wright, Gary Sinise", ["Drama", "Romance"], "A kindhearted man moves through major American moments while holding onto love and hope."),
  movie("Fight Club", 1999, 139, "David Fincher", "Jim Uhls", "Edward Norton, Brad Pitt, Helena Bonham Carter", ["Drama", "Thriller"], "An alienated office worker enters a violent underground world that spirals out of control."),
  movie("Inception", 2010, 148, "Christopher Nolan", "Christopher Nolan", "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page", ["Action", "Science Fiction", "Thriller"], "A thief who enters dreams takes on a risky job built around planting an idea."),
  movie("The Matrix", 1999, 136, "Lana Wachowski, Lilly Wachowski", "Lana Wachowski, Lilly Wachowski", "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss", ["Action", "Science Fiction"], "A hacker discovers reality is a constructed system and joins a rebellion against its controllers."),
  movie("Goodfellas", 1990, 146, "Martin Scorsese", "Nicholas Pileggi, Martin Scorsese", "Robert De Niro, Ray Liotta, Joe Pesci", ["Crime", "Drama"], "A mob associate rises through organized crime and watches the life consume him."),
  movie("Star Wars: Episode IV - A New Hope", 1977, 121, "George Lucas", "George Lucas", "Mark Hamill, Harrison Ford, Carrie Fisher", ["Adventure", "Science Fiction"], "A farm boy joins rebels, smugglers, and a princess in a fight against an empire."),
  movie("Star Wars: Episode V - The Empire Strikes Back", 1980, 124, "Irvin Kershner", "Leigh Brackett, Lawrence Kasdan", "Mark Hamill, Harrison Ford, Carrie Fisher", ["Adventure", "Science Fiction"], "The rebellion is hunted while Luke seeks training and faces a painful truth."),
  movie("Star Wars: Episode VI - Return of the Jedi", 1983, 131, "Richard Marquand", "Lawrence Kasdan, George Lucas", "Mark Hamill, Harrison Ford, Carrie Fisher", ["Adventure", "Science Fiction"], "The rebels launch a final attack while Luke confronts Vader and the Emperor."),
  movie("Jurassic Park", 1993, 127, "Steven Spielberg", "Michael Crichton, David Koepp", "Sam Neill, Laura Dern, Jeff Goldblum", ["Adventure", "Science Fiction", "Thriller"], "A dinosaur theme park becomes a survival nightmare when its systems fail."),
  movie("Jaws", 1975, 124, "Steven Spielberg", "Peter Benchley, Carl Gottlieb", "Roy Scheider, Robert Shaw, Richard Dreyfuss", ["Adventure", "Horror", "Thriller"], "A coastal town is terrorized by a great white shark during tourist season."),
  movie("Raiders of the Lost Ark", 1981, 115, "Steven Spielberg", "Lawrence Kasdan", "Harrison Ford, Karen Allen, Paul Freeman", ["Action", "Adventure"], "An archaeologist races enemy agents to recover a powerful ancient artifact."),
  movie("Back to the Future", 1985, 116, "Robert Zemeckis", "Robert Zemeckis, Bob Gale", "Michael J. Fox, Christopher Lloyd, Lea Thompson", ["Adventure", "Comedy", "Science Fiction"], "A teenager accidentally travels to the past and must repair his parents' future."),
  movie("E.T. the Extra-Terrestrial", 1982, 115, "Steven Spielberg", "Melissa Mathison", "Henry Thomas, Drew Barrymore, Dee Wallace", ["Family", "Science Fiction"], "A lonely child befriends a stranded alien and helps him return home."),
  movie("Alien", 1979, 117, "Ridley Scott", "Dan O'Bannon", "Sigourney Weaver, Tom Skerritt, John Hurt", ["Horror", "Science Fiction"], "A space crew answers a distress signal and brings a lethal organism aboard."),
  movie("Aliens", 1986, 137, "James Cameron", "James Cameron", "Sigourney Weaver, Michael Biehn, Carrie Henn", ["Action", "Science Fiction", "Thriller"], "Ripley returns with marines to face a colony overrun by alien creatures."),
  movie("Terminator 2: Judgment Day", 1991, 137, "James Cameron", "James Cameron, William Wisher", "Arnold Schwarzenegger, Linda Hamilton, Edward Furlong", ["Action", "Science Fiction"], "A reprogrammed machine protects a boy who may shape humanity's future."),
  movie("Gladiator", 2000, 155, "Ridley Scott", "David Franzoni, John Logan, William Nicholson", "Russell Crowe, Joaquin Phoenix, Connie Nielsen", ["Action", "Drama", "History"], "A betrayed Roman general becomes a gladiator and seeks justice in the arena."),
  movie("Braveheart", 1995, 178, "Mel Gibson", "Randall Wallace", "Mel Gibson, Sophie Marceau, Patrick McGoohan", ["Action", "Drama", "History"], "A Scottish rebel leader fights English rule and becomes a symbol of freedom."),
  movie("Saving Private Ryan", 1998, 169, "Steven Spielberg", "Robert Rodat", "Tom Hanks, Matt Damon, Tom Sizemore", ["Drama", "War"], "A small unit crosses wartime France to bring home a soldier whose brothers have died."),
  movie("The Silence of the Lambs", 1991, 118, "Jonathan Demme", "Ted Tally", "Jodie Foster, Anthony Hopkins, Scott Glenn", ["Crime", "Thriller", "Horror"], "An FBI trainee consults a brilliant imprisoned killer to catch another murderer."),
  movie("Se7en", 1995, 127, "David Fincher", "Andrew Kevin Walker", "Brad Pitt, Morgan Freeman, Gwyneth Paltrow", ["Crime", "Mystery", "Thriller"], "Two detectives track a killer staging murders around the seven deadly sins."),
  movie("The Usual Suspects", 1995, 106, "Bryan Singer", "Christopher McQuarrie", "Kevin Spacey, Gabriel Byrne, Benicio del Toro", ["Crime", "Mystery", "Thriller"], "A survivor's story pulls investigators into a maze around a legendary criminal."),
  movie("The Departed", 2006, 151, "Martin Scorsese", "William Monahan", "Leonardo DiCaprio, Matt Damon, Jack Nicholson", ["Crime", "Drama", "Thriller"], "An undercover cop and a police mole try to uncover each other in Boston."),
  movie("Heat", 1995, 170, "Michael Mann", "Michael Mann", "Al Pacino, Robert De Niro, Val Kilmer", ["Action", "Crime", "Drama"], "A relentless detective pursues a meticulous thief preparing one last major score."),
  movie("Casino", 1995, 178, "Martin Scorsese", "Nicholas Pileggi, Martin Scorsese", "Robert De Niro, Sharon Stone, Joe Pesci", ["Crime", "Drama"], "A gambling empire in Las Vegas is strained by greed, violence, and betrayal."),
  movie("The Green Mile", 1999, 189, "Frank Darabont", "Frank Darabont", "Tom Hanks, Michael Clarke Duncan, David Morse", ["Drama", "Fantasy"], "Death row guards encounter a gentle prisoner with a mysterious gift."),
  movie("The Prestige", 2006, 130, "Christopher Nolan", "Jonathan Nolan, Christopher Nolan", "Christian Bale, Hugh Jackman, Scarlett Johansson", ["Drama", "Mystery", "Science Fiction"], "Two rival magicians sacrifice more and more in pursuit of the perfect illusion."),
  movie("Memento", 2000, 113, "Christopher Nolan", "Christopher Nolan", "Guy Pearce, Carrie-Anne Moss, Joe Pantoliano", ["Mystery", "Thriller"], "A man with short-term memory loss follows clues to solve his wife's murder."),
  movie("Interstellar", 2014, 169, "Christopher Nolan", "Jonathan Nolan, Christopher Nolan", "Matthew McConaughey, Anne Hathaway, Jessica Chastain", ["Adventure", "Drama", "Science Fiction"], "Explorers travel through a wormhole to search for a future home for humanity."),
  movie("Dunkirk", 2017, 106, "Christopher Nolan", "Christopher Nolan", "Fionn Whitehead, Tom Hardy, Mark Rylance", ["Drama", "History", "War"], "Soldiers, civilians, and pilots converge during the evacuation of Allied troops."),
  movie("Oppenheimer", 2023, 180, "Christopher Nolan", "Christopher Nolan", "Cillian Murphy, Emily Blunt, Robert Downey Jr.", ["Drama", "History"], "A physicist helps build the atomic bomb and faces the consequences of his work."),
  movie("Parasite", 2019, 132, "Bong Joon Ho", "Bong Joon Ho, Han Jin-won", "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong", ["Drama", "Thriller", "Comedy"], "A poor family infiltrates a wealthy household, exposing class tensions with sharp twists."),
  movie("Spirited Away", 2001, 125, "Hayao Miyazaki", "Hayao Miyazaki", "Rumi Hiiragi, Miyu Irino, Mari Natsuki", ["Animation", "Adventure", "Fantasy"], "A girl enters a spirit world and must find courage to save her parents."),
  movie("Princess Mononoke", 1997, 134, "Hayao Miyazaki", "Hayao Miyazaki", "Yoji Matsuda, Yuriko Ishida, Yuko Tanaka", ["Animation", "Adventure", "Fantasy"], "A young warrior becomes caught between industrial ambition and forest spirits."),
  movie("My Neighbor Totoro", 1988, 86, "Hayao Miyazaki", "Hayao Miyazaki", "Noriko Hidaka, Chika Sakamoto, Hitoshi Takagi", ["Animation", "Family", "Fantasy"], "Two sisters move to the countryside and meet gentle spirits near their new home."),
  movie("Toy Story", 1995, 81, "John Lasseter", "Joss Whedon, Andrew Stanton", "Tom Hanks, Tim Allen, Don Rickles", ["Animation", "Adventure", "Comedy"], "A favorite toy feels threatened when a flashy space ranger joins the bedroom."),
  movie("Toy Story 3", 2010, 103, "Lee Unkrich", "Michael Arndt", "Tom Hanks, Tim Allen, Joan Cusack", ["Animation", "Comedy", "Family"], "Andy's toys face an uncertain future as he prepares to leave for college."),
  movie("Finding Nemo", 2003, 100, "Andrew Stanton", "Andrew Stanton, Bob Peterson, David Reynolds", "Albert Brooks, Ellen DeGeneres, Alexander Gould", ["Animation", "Adventure", "Family"], "A cautious clownfish crosses the ocean to find his missing son."),
  movie("WALL-E", 2008, 98, "Andrew Stanton", "Andrew Stanton, Jim Reardon", "Ben Burtt, Elissa Knight, Jeff Garlin", ["Animation", "Adventure", "Science Fiction"], "A lonely cleanup robot discovers a new purpose after meeting a sleek probe."),
  movie("Up", 2009, 96, "Pete Docter", "Bob Peterson, Pete Docter", "Ed Asner, Jordan Nagai, Christopher Plummer", ["Animation", "Adventure", "Family"], "An elderly widower lifts his house into the sky and finds an unexpected companion."),
  movie("The Lion King", 1994, 88, "Roger Allers, Rob Minkoff", "Irene Mecchi, Jonathan Roberts, Linda Woolverton", "Matthew Broderick, James Earl Jones, Jeremy Irons", ["Animation", "Adventure", "Family"], "A young lion prince grows into his destiny after exile and loss."),
  movie("Beauty and the Beast", 1991, 84, "Gary Trousdale, Kirk Wise", "Linda Woolverton", "Paige O'Hara, Robby Benson, Angela Lansbury", ["Animation", "Family", "Musical"], "A book-loving young woman discovers kindness inside an enchanted castle."),
  movie("The Social Network", 2010, 120, "David Fincher", "Aaron Sorkin", "Jesse Eisenberg, Andrew Garfield, Justin Timberlake", ["Drama"], "The rise of a social media company brings ambition, lawsuits, and broken friendships."),
  movie("The Wolf of Wall Street", 2013, 180, "Martin Scorsese", "Terence Winter", "Leonardo DiCaprio, Jonah Hill, Margot Robbie", ["Comedy", "Crime", "Drama"], "A stockbroker builds a reckless empire through fraud, excess, and charisma."),
  movie("Whiplash", 2014, 106, "Damien Chazelle", "Damien Chazelle", "Miles Teller, J.K. Simmons, Melissa Benoist", ["Drama", "Musical"], "An ambitious drummer clashes with a ruthless teacher who demands perfection."),
  movie("La La Land", 2016, 128, "Damien Chazelle", "Damien Chazelle", "Ryan Gosling, Emma Stone, John Legend", ["Drama", "Musical", "Romance"], "Two artists fall in love while chasing dreams in Los Angeles."),
  movie("Moonlight", 2016, 111, "Barry Jenkins", "Barry Jenkins, Tarell Alvin McCraney", "Trevante Rhodes, Andre Holland, Janelle Monae", ["Drama"], "A young man grows through three chapters while searching for identity and connection."),
  movie("Get Out", 2017, 104, "Jordan Peele", "Jordan Peele", "Daniel Kaluuya, Allison Williams, Bradley Whitford", ["Horror", "Mystery", "Thriller"], "A weekend visit reveals disturbing secrets beneath a wealthy family's politeness."),
  movie("Us", 2019, 116, "Jordan Peele", "Jordan Peele", "Lupita Nyong'o, Winston Duke, Elisabeth Moss", ["Horror", "Mystery", "Thriller"], "A family's vacation turns terrifying when uncanny doubles appear at their door."),
  movie("No Country for Old Men", 2007, 122, "Joel Coen, Ethan Coen", "Joel Coen, Ethan Coen", "Tommy Lee Jones, Javier Bardem, Josh Brolin", ["Crime", "Drama", "Thriller"], "A hunter finds drug money and is pursued by a remorseless killer."),
  movie("Fargo", 1996, 98, "Joel Coen", "Joel Coen, Ethan Coen", "Frances McDormand, William H. Macy, Steve Buscemi", ["Crime", "Drama", "Comedy"], "A clumsy kidnapping plot unravels under the eye of a sharp Minnesota police chief."),
  movie("The Big Lebowski", 1998, 117, "Joel Coen", "Joel Coen, Ethan Coen", "Jeff Bridges, John Goodman, Julianne Moore", ["Comedy", "Crime"], "A laid-back bowler is pulled into a strange ransom scheme after a case of mistaken identity."),
  movie("Blade Runner", 1982, 117, "Ridley Scott", "Hampton Fancher, David Webb Peoples", "Harrison Ford, Rutger Hauer, Sean Young", ["Science Fiction", "Thriller"], "A weary detective hunts synthetic humans in a rain-soaked future Los Angeles."),
  movie("Blade Runner 2049", 2017, 164, "Denis Villeneuve", "Hampton Fancher, Michael Green", "Ryan Gosling, Harrison Ford, Ana de Armas", ["Science Fiction", "Drama", "Mystery"], "A replicant officer uncovers a secret that could reshape society."),
  movie("Arrival", 2016, 116, "Denis Villeneuve", "Eric Heisserer", "Amy Adams, Jeremy Renner, Forest Whitaker", ["Drama", "Mystery", "Science Fiction"], "A linguist works to communicate with aliens before fear turns into conflict."),
  movie("Dune", 2021, 155, "Denis Villeneuve", "Jon Spaihts, Denis Villeneuve, Eric Roth", "Timothee Chalamet, Rebecca Ferguson, Oscar Isaac", ["Adventure", "Drama", "Science Fiction"], "A noble heir enters a desert world central to politics, prophecy, and survival."),
  movie("Mad Max: Fury Road", 2015, 120, "George Miller", "George Miller, Brendan McCarthy, Nico Lathouris", "Tom Hardy, Charlize Theron, Nicholas Hoult", ["Action", "Adventure", "Science Fiction"], "A road warrior and a rebel driver flee a tyrant across a brutal wasteland."),
  movie("The Grand Budapest Hotel", 2014, 99, "Wes Anderson", "Wes Anderson", "Ralph Fiennes, Tony Revolori, Saoirse Ronan", ["Comedy", "Drama"], "A concierge and lobby boy are swept into theft, murder, and old-world elegance."),
  movie("The Truman Show", 1998, 103, "Peter Weir", "Andrew Niccol", "Jim Carrey, Laura Linney, Ed Harris", ["Comedy", "Drama", "Science Fiction"], "A cheerful man begins to suspect his entire life is a television production."),
  movie("Eternal Sunshine of the Spotless Mind", 2004, 108, "Michel Gondry", "Charlie Kaufman", "Jim Carrey, Kate Winslet, Kirsten Dunst", ["Drama", "Romance", "Science Fiction"], "Former lovers erase memories of each other but find emotions harder to remove."),
  movie("Her", 2013, 126, "Spike Jonze", "Spike Jonze", "Joaquin Phoenix, Scarlett Johansson, Amy Adams", ["Drama", "Romance", "Science Fiction"], "A lonely writer develops a relationship with an advanced operating system."),
  movie("The Sixth Sense", 1999, 107, "M. Night Shyamalan", "M. Night Shyamalan", "Bruce Willis, Haley Joel Osment, Toni Collette", ["Drama", "Mystery", "Thriller"], "A child psychologist tries to help a boy haunted by unsettling visions."),
  movie("The Shining", 1980, 146, "Stanley Kubrick", "Stanley Kubrick, Diane Johnson", "Jack Nicholson, Shelley Duvall, Danny Lloyd", ["Horror", "Drama"], "A family isolated in a mountain hotel is threatened by madness and supernatural forces."),
  movie("A Clockwork Orange", 1971, 136, "Stanley Kubrick", "Stanley Kubrick", "Malcolm McDowell, Patrick Magee, Adrienne Corri", ["Crime", "Drama", "Science Fiction"], "A violent young criminal becomes the subject of a disturbing state experiment."),
  movie("2001: A Space Odyssey", 1968, 149, "Stanley Kubrick", "Stanley Kubrick, Arthur C. Clarke", "Keir Dullea, Gary Lockwood, William Sylvester", ["Adventure", "Science Fiction"], "Human evolution and artificial intelligence intersect on a mysterious space mission."),
  movie("Apocalypse Now", 1979, 147, "Francis Ford Coppola", "John Milius, Francis Ford Coppola", "Martin Sheen, Marlon Brando, Robert Duvall", ["Drama", "War"], "A soldier travels upriver during war to confront a colonel who has gone rogue."),
  movie("Taxi Driver", 1976, 114, "Martin Scorsese", "Paul Schrader", "Robert De Niro, Jodie Foster, Cybill Shepherd", ["Crime", "Drama"], "An isolated veteran working nights in New York spirals toward violence."),
  movie("Raging Bull", 1980, 129, "Martin Scorsese", "Paul Schrader, Mardik Martin", "Robert De Niro, Cathy Moriarty, Joe Pesci", ["Drama"], "A brilliant boxer's rage damages his career, marriage, and sense of self."),
  movie("Rocky", 1976, 120, "John G. Avildsen", "Sylvester Stallone", "Sylvester Stallone, Talia Shire, Burt Young", ["Drama", "Romance"], "An underdog boxer gets a rare title shot and fights for dignity."),
  movie("Die Hard", 1988, 132, "John McTiernan", "Jeb Stuart, Steven E. de Souza", "Bruce Willis, Alan Rickman, Bonnie Bedelia", ["Action", "Thriller"], "A New York cop battles armed thieves inside a Los Angeles skyscraper."),
  movie("Lethal Weapon", 1987, 109, "Richard Donner", "Shane Black", "Mel Gibson, Danny Glover, Gary Busey", ["Action", "Crime", "Comedy"], "Two mismatched detectives uncover a dangerous smuggling operation."),
  movie("The Princess Bride", 1987, 98, "Rob Reiner", "William Goldman", "Cary Elwes, Robin Wright, Mandy Patinkin", ["Adventure", "Comedy", "Fantasy"], "A farmhand's quest to rescue his true love becomes a playful fairy-tale adventure."),
  movie("Stand by Me", 1986, 89, "Rob Reiner", "Bruce A. Evans, Raynold Gideon", "Wil Wheaton, River Phoenix, Corey Feldman", ["Adventure", "Drama"], "Four boys take a life-changing walk in search of a missing child's body."),
  movie("When Harry Met Sally...", 1989, 95, "Rob Reiner", "Nora Ephron", "Billy Crystal, Meg Ryan, Carrie Fisher", ["Comedy", "Romance"], "Two friends repeatedly cross paths while debating whether friendship can become love."),
  movie("Groundhog Day", 1993, 101, "Harold Ramis", "Danny Rubin, Harold Ramis", "Bill Murray, Andie MacDowell, Chris Elliott", ["Comedy", "Fantasy", "Romance"], "A cynical weather reporter relives the same day until he begins to change."),
  movie("Ghostbusters", 1984, 105, "Ivan Reitman", "Dan Aykroyd, Harold Ramis", "Bill Murray, Dan Aykroyd, Sigourney Weaver", ["Comedy", "Fantasy"], "Paranormal investigators become unlikely heroes when New York faces a spectral threat."),
  movie("The Breakfast Club", 1985, 97, "John Hughes", "John Hughes", "Emilio Estevez, Molly Ringwald, Judd Nelson", ["Comedy", "Drama"], "Five high school students discover unexpected common ground during Saturday detention."),
  movie("Ferris Bueller's Day Off", 1986, 103, "John Hughes", "John Hughes", "Matthew Broderick, Alan Ruck, Mia Sara", ["Comedy"], "A charming teenager skips school for an elaborate day around Chicago."),
  movie("The Exorcist", 1973, 122, "William Friedkin", "William Peter Blatty", "Ellen Burstyn, Max von Sydow, Linda Blair", ["Horror"], "A mother seeks help when her daughter appears possessed by a malicious force."),
  movie("Halloween", 1978, 91, "John Carpenter", "John Carpenter, Debra Hill", "Jamie Lee Curtis, Donald Pleasence, Nick Castle", ["Horror", "Thriller"], "A masked killer stalks babysitters on Halloween night."),
  movie("A Nightmare on Elm Street", 1984, 91, "Wes Craven", "Wes Craven", "Heather Langenkamp, Robert Englund, Johnny Depp", ["Horror"], "Teenagers are attacked in their dreams by a vengeful figure with knives for fingers."),
  movie("The Thing", 1982, 109, "John Carpenter", "Bill Lancaster", "Kurt Russell, Wilford Brimley, Keith David", ["Horror", "Science Fiction"], "Researchers in Antarctica confront a shape-shifting organism that breeds paranoia."),
  movie("Pan's Labyrinth", 2006, 118, "Guillermo del Toro", "Guillermo del Toro", "Ivana Baquero, Sergi Lopez, Maribel Verdu", ["Drama", "Fantasy", "War"], "A young girl escapes brutal reality through a dark and dangerous fairy-tale world."),
  movie("The Shape of Water", 2017, 123, "Guillermo del Toro", "Guillermo del Toro, Vanessa Taylor", "Sally Hawkins, Michael Shannon, Octavia Spencer", ["Drama", "Fantasy", "Romance"], "A mute cleaner forms a bond with an amphibious captive in a secret facility."),
  movie("Amelie", 2001, 122, "Jean-Pierre Jeunet", "Guillaume Laurant, Jean-Pierre Jeunet", "Audrey Tautou, Mathieu Kassovitz, Rufus", ["Comedy", "Romance"], "A shy Parisian waitress quietly changes lives while searching for her own happiness."),
  movie("Life Is Beautiful", 1997, 116, "Roberto Benigni", "Vincenzo Cerami, Roberto Benigni", "Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini", ["Comedy", "Drama", "War"], "A father uses imagination to shield his son from the horrors around them."),
  movie("Cinema Paradiso", 1988, 155, "Giuseppe Tornatore", "Giuseppe Tornatore", "Philippe Noiret, Salvatore Cascio, Marco Leonardi", ["Drama", "Romance"], "A filmmaker recalls the projectionist and movie theater that shaped his childhood."),
  movie("Crouching Tiger, Hidden Dragon", 2000, 120, "Ang Lee", "Wang Hui-ling, James Schamus, Kuo Jung Tsai", "Chow Yun-fat, Michelle Yeoh, Zhang Ziyi", ["Action", "Adventure", "Drama"], "Warriors and lovers pursue a stolen sword through graceful, dangerous confrontations."),
  movie("Oldboy", 2003, 120, "Park Chan-wook", "Hwang Jo-yun, Lim Joon-hyung, Park Chan-wook", "Choi Min-sik, Yoo Ji-tae, Kang Hye-jung", ["Action", "Drama", "Mystery"], "A man released after years of captivity searches for the reason behind his imprisonment."),
  movie("City of God", 2002, 130, "Fernando Meirelles, Katia Lund", "Braulio Mantovani", "Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen", ["Crime", "Drama"], "Young people grow up amid violence and ambition in Rio de Janeiro's favelas."),
  movie("The Lives of Others", 2006, 137, "Florian Henckel von Donnersmarck", "Florian Henckel von Donnersmarck", "Ulrich Muhe, Martina Gedeck, Sebastian Koch", ["Drama", "Thriller"], "A surveillance officer in East Germany becomes emotionally drawn to the lives he monitors."),
];
